clear
clc
yuvname_seq2={'akiyo_qcif.yuv','bridge_qcif.yuv','bus_qcif.yuv','carphone_qcif.yuv',...
         'coastguard_qcif.yuv','container_qcif.yuv','football_qcif.yuv','foreman_qcif.yuv',...
         'grandma_qcif.yuv','hall_qcif.yuv','harbour_qcif.yuv','highway_qcif.yuv',...
         'ice_qcif.yuv','mobile_qcif.yuv','news_qcif.yuv','salesman_qcif.yuv',...
         'silent_qcif.yuv','soccer_qcif.yuv','stefan_qcif.yuv','suzie_qcif.yuv'};
seqList=[5 7 8 13 14 18 19];
yuvname=yuvname_seq2(seqList);
len=length(yuvname);

avgdata_all_mserdo;
qp=28:42;
linespec={'*r-','*g-','*b-','*y-','*c-','or-','og-','ob-','xr-','xg-','xb-'};
avgdata={
          'avgdata_all_stvssimrdo_lam3_1',...
          'avgdata_all_stvssimrdo_lam3_2',...
         'avgdata_all_stvssimrdo_lam3_3',...
         'avgdata_all_stvssimrdo_lam3_4',...
         'avgdata_all_stvssimrdo_lam3_5',...
         'avgdata_all_stvssimrdo_lam3_7',...
%        'avgdata_all_stvssimrdo_lam3_11',...
%       'avgdata_all_stvssimrdo_lam3_12',...
%       'avgdata_all_stvssimrdo_lam3_13',...
%       'avgdata_all_stvssimrdo_lam3_14',...
%       'avgdata_all_stvssimrdo_lam3_15',...
%       'avgdata_all_stvssimrdo_lam1_2',...
%         'avgdata_all_stvssimrdo_lam3_7',...
%         'avgdata_all_stvssimrdo_lam3_8',...
%         'avgdata_all_stvssimrdo_lam3_9',...
%         'avgdata_all_stvssimrdo_lam3_10'...
%          'avgdata_all_stvssimrdo_lam2_1',...
%          'avgdata_all_stvssimrdo_lam2_2',...
%          'avgdata_all_stvssimrdo_lam2_3',...
%          'avgdata_all_stvssimrdo_lam2_4',...
         };
len2=length(avgdata);
seq2=1:len2;
%%
for i=1:len
    seqname=yuvname{i}(1:end-4);
    aa_mserdo=[seqname '_avg_mserdo'];
    eval(['avg_mserdo=' aa_mserdo ';']);
    figure('name',[seqname '_stvssim_rate'])
    grid on
    hold on 
    rate=avg_mserdo(:,10)*30/49000;
    stvssimY=avg_mserdo(:,7);
    plot(rate,stvssimY,'*k-');
    aa_stvssimrdo=[seqname '_avg_stvssimrdo'];
    for j=seq2
        eval([avgdata{j} ';']);
        %eval(avgdata{j});
        eval(['avg_stvssimrdo=' aa_stvssimrdo ';']);
        rate=avg_stvssimrdo(:,10)*30/49000;
        stvssimY=avg_stvssimrdo(:,7);
        plot(rate,stvssimY,linespec{j});
    end
   
    pause
end

